spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yingchuanfu/springcloud_config/sell-repo
          username: 245160096@qq.com
          password: Yingchuanfu1995
eureka:
  client:
    service-url:
    defaultzone: http://localhost:8761/eureka/